REGISTRY_OPENGL(PFNGLGETINTEGERVPROC, GetIntegerv)
REGISTRY_OPENGL(PFNGLGETSTRINGIPROC, GetStringi)

REGISTRY_OPENGL(PFNGLCLIPCONTROLPROC, ClipControl)

REGISTRY_OPENGL(PFNGLDISABLEPROC, Enable)
REGISTRY_OPENGL(PFNGLENABLEPROC,  Disable)

REGISTRY_OPENGL(PFNGLDEPTHMASKPROC,   DepthMask)
REGISTRY_OPENGL(PFNGLDEPTHRANGEFPROC, DepthRangef)
REGISTRY_OPENGL(PFNGLDEPTHRANGEPROC,  DepthRange)
REGISTRY_OPENGL(PFNGLDEPTHFUNCPROC,   DepthFunc)
REGISTRY_OPENGL(PFNGLCLEARDEPTHFPROC, ClearDepthf)
REGISTRY_OPENGL(PFNGLCLEARDEPTHPROC,  ClearDepth)

REGISTRY_OPENGL(PFNGLCOLORMASKPROC,  ColorMask)
REGISTRY_OPENGL(PFNGLCLEARCOLORPROC, ClearColor)
REGISTRY_OPENGL(PFNGLBLENDFUNCIPROC, BlendFunc)

REGISTRY_OPENGL(PFNGLCULLFACEPROC,  CullFace)
REGISTRY_OPENGL(PFNGLFRONTFACEPROC, FrontFace)

REGISTRY_OPENGL(PFNGLCLEARSTENCILPROC, ClearStencil)
REGISTRY_OPENGL(PFNGLSTENCILMASKPROC,  StencilMask)
REGISTRY_OPENGL(PFNGLSTENCILFUNCPROC,  StencilFunc)
REGISTRY_OPENGL(PFNGLSTENCILOPPROC,    StencilOp)

REGISTRY_OPENGL(PFNGLCREATEPROGRAMPROC, CreateProgram)

REGISTRY_OPENGL(PFNGLFINISHPROC, Finish)
REGISTRY_OPENGL(PFNGLFLUSHPROC,  Flush)
#undef REGISTRY_OPENGL
