// EXTENSIONS
REGISTRY_OPENGL(PFNGLGETINTEGERVPROC, GetIntegerv)
REGISTRY_OPENGL(PFNGLGETSTRINGIPROC,  GetStringi)

// SETTINGS
REGISTRY_OPENGL(PFNGLVIEWPORTPROC, Viewport)

REGISTRY_OPENGL(PFNGLCLIPCONTROLPROC, ClipControl) // >= 4.5

REGISTRY_OPENGL(PFNGLDISABLEPROC, Disable)
REGISTRY_OPENGL(PFNGLENABLEPROC,  Enable)

REGISTRY_OPENGL(PFNGLDEPTHMASKPROC,   DepthMask)
REGISTRY_OPENGL(PFNGLDEPTHRANGEPROC,  DepthRange)  // >= 2.0
REGISTRY_OPENGL(PFNGLDEPTHRANGEFPROC, DepthRangef) // >= 4.1
REGISTRY_OPENGL(PFNGLDEPTHFUNCPROC,   DepthFunc)
REGISTRY_OPENGL(PFNGLCLEARDEPTHPROC,  ClearDepth)  // >= 2.0
REGISTRY_OPENGL(PFNGLCLEARDEPTHFPROC, ClearDepthf) // >= 4.1

REGISTRY_OPENGL(PFNGLCOLORMASKPROC,  ColorMask)
REGISTRY_OPENGL(PFNGLCLEARCOLORPROC, ClearColor)
REGISTRY_OPENGL(PFNGLBLENDFUNCIPROC, BlendFunc)

REGISTRY_OPENGL(PFNGLCULLFACEPROC,  CullFace)
REGISTRY_OPENGL(PFNGLFRONTFACEPROC, FrontFace)

REGISTRY_OPENGL(PFNGLCLEARSTENCILPROC, ClearStencil)
REGISTRY_OPENGL(PFNGLSTENCILMASKPROC,  StencilMask)
REGISTRY_OPENGL(PFNGLSTENCILFUNCPROC,  StencilFunc)
REGISTRY_OPENGL(PFNGLSTENCILOPPROC,    StencilOp)

// PROGRAMS (a whole GPU program)
REGISTRY_OPENGL(PFNGLCREATEPROGRAMPROC,     CreateProgram)
REGISTRY_OPENGL(PFNGLDELETEPROGRAMPROC,     DeleteProgram)
REGISTRY_OPENGL(PFNGLUSEPROGRAMPROC,        UseProgram)
REGISTRY_OPENGL(PFNGLLINKPROGRAMPROC,       LinkProgram)
REGISTRY_OPENGL(PFNGLGETPROGRAMIVPROC,      GetProgramiv)
REGISTRY_OPENGL(PFNGLGETPROGRAMINFOLOGPROC, GetProgramInfoLog)
REGISTRY_OPENGL(PFNGLGETPROGRAMBINARYPROC,  GetProgramBinary)

// SHADERS (a part of a GPU program)
REGISTRY_OPENGL(PFNGLCREATESHADERPROC,      CreateShader)
REGISTRY_OPENGL(PFNGLDELETESHADERPROC,      DeleteShader)
REGISTRY_OPENGL(PFNGLSHADERSOURCEPROC,      ShaderSource)
REGISTRY_OPENGL(PFNGLCOMPILESHADERPROC,     CompileShader)
REGISTRY_OPENGL(PFNGLATTACHSHADERPROC,      AttachShader)
REGISTRY_OPENGL(PFNGLDETACHSHADERPROC,      DetachShader)
REGISTRY_OPENGL(PFNGLGETSHADERIVPROC,       GetShaderiv)
REGISTRY_OPENGL(PFNGLGETSHADERINFOLOGPROC,  GetShaderInfoLog)
REGISTRY_OPENGL(PFNGLGETSHADERSOURCEPROC,   GetShaderSource)

// ATTRIBUTES (GPU program vertex locations)
REGISTRY_OPENGL(PFNGLGETACTIVEATTRIBPROC,   GetActiveAttrib)
REGISTRY_OPENGL(PFNGLGETATTRIBLOCATIONPROC, GetAttribLocation)

// UNIFORMS (GPU program variables and constants)
REGISTRY_OPENGL(PFNGLGETACTIVEUNIFORMPROC,   GetActiveUniform)
REGISTRY_OPENGL(PFNGLGETUNIFORMLOCATIONPROC, GetUniformLocation)
REGISTRY_OPENGL(PFNGLUNIFORM1FVPROC, Uniform1fv)
REGISTRY_OPENGL(PFNGLUNIFORM2FVPROC, Uniform2fv)
REGISTRY_OPENGL(PFNGLUNIFORM3FVPROC, Uniform3fv)
REGISTRY_OPENGL(PFNGLUNIFORM4FVPROC, Uniform4fv)
REGISTRY_OPENGL(PFNGLUNIFORM1IVPROC,  Uniform1iv) // also a sampler uniform
REGISTRY_OPENGL(PFNGLUNIFORM2IVPROC,  Uniform2iv)
REGISTRY_OPENGL(PFNGLUNIFORM3IVPROC,  Uniform3iv)
REGISTRY_OPENGL(PFNGLUNIFORM4IVPROC,  Uniform4iv)
REGISTRY_OPENGL(PFNGLUNIFORMMATRIX2FVPROC, UniformMatrix2fv)
REGISTRY_OPENGL(PFNGLUNIFORMMATRIX3FVPROC, UniformMatrix3fv)
REGISTRY_OPENGL(PFNGLUNIFORMMATRIX4FVPROC, UniformMatrix4fv)
// >= 3.0
REGISTRY_OPENGL(PFNGLUNIFORM1UIVPROC, Uniform1uiv)
REGISTRY_OPENGL(PFNGLUNIFORM2UIVPROC, Uniform2uiv)
REGISTRY_OPENGL(PFNGLUNIFORM3UIVPROC, Uniform3uiv)
REGISTRY_OPENGL(PFNGLUNIFORM4UIVPROC, Uniform4uiv)
// >= 4.1
REGISTRY_OPENGL(PFNGLPROGRAMUNIFORM1FVPROC, ProgramUniform1fv)
REGISTRY_OPENGL(PFNGLPROGRAMUNIFORM2FVPROC, ProgramUniform2fv)
REGISTRY_OPENGL(PFNGLPROGRAMUNIFORM3FVPROC, ProgramUniform3fv)
REGISTRY_OPENGL(PFNGLPROGRAMUNIFORM4FVPROC, ProgramUniform4fv)
REGISTRY_OPENGL(PFNGLPROGRAMUNIFORM1IVPROC,  ProgramUniform1iv) // also a sampler uniform
REGISTRY_OPENGL(PFNGLPROGRAMUNIFORM2IVPROC,  ProgramUniform2iv)
REGISTRY_OPENGL(PFNGLPROGRAMUNIFORM3IVPROC,  ProgramUniform3iv)
REGISTRY_OPENGL(PFNGLPROGRAMUNIFORM4IVPROC,  ProgramUniform4iv)
REGISTRY_OPENGL(PFNGLPROGRAMUNIFORM1UIVPROC,  ProgramUniform1uiv)
REGISTRY_OPENGL(PFNGLPROGRAMUNIFORM2UIVPROC,  ProgramUniform2uiv)
REGISTRY_OPENGL(PFNGLPROGRAMUNIFORM3UIVPROC,  ProgramUniform3uiv)
REGISTRY_OPENGL(PFNGLPROGRAMUNIFORM4UIVPROC,  ProgramUniform4uiv)
REGISTRY_OPENGL(PFNGLPROGRAMUNIFORMMATRIX2FVPROC, ProgramUniformMatrix2fv)
REGISTRY_OPENGL(PFNGLPROGRAMUNIFORMMATRIX3FVPROC, ProgramUniformMatrix3fv)
REGISTRY_OPENGL(PFNGLPROGRAMUNIFORMMATRIX4FVPROC, ProgramUniformMatrix4fv)

// TEXTURES
// >= 2.0
REGISTRY_OPENGL(PFNGLGENTEXTURESPROC,    GenTextures)
REGISTRY_OPENGL(PFNGLDELETETEXTURESPROC, DeleteTextures)
REGISTRY_OPENGL(PFNGLACTIVETEXTUREPROC,  ActiveTexture)
REGISTRY_OPENGL(PFNGLBINDTEXTUREPROC,    BindTexture)
REGISTRY_OPENGL(PFNGLTEXIMAGE2DPROC,     TexImage2D)
REGISTRY_OPENGL(PFNGLTEXPARAMETERIPROC,  TexParameteri)
REGISTRY_OPENGL(PFNGLTEXSUBIMAGE2DPROC,  TexSubImage2D)
// >= 4.2
REGISTRY_OPENGL(PFNGLTEXSTORAGE2DPROC, TexStorage2D)
// >= 4.5
REGISTRY_OPENGL(PFNGLCREATETEXTURESPROC,    CreateTextures)
REGISTRY_OPENGL(PFNGLTEXTURESTORAGE2DPROC,  TextureStorage2D)
REGISTRY_OPENGL(PFNGLTEXTUREPARAMETERIPROC, TextureParameteri)
REGISTRY_OPENGL(PFNGLBINDTEXTUREUNITPROC,   BindTextureUnit)
REGISTRY_OPENGL(PFNGLTEXTURESUBIMAGE2DPROC, TextureSubImage2D)

// SAMPLERS
// >= 3.2
REGISTRY_OPENGL(PFNGLGENSAMPLERSPROC,       GenSamplers)
REGISTRY_OPENGL(PFNGLDELETESAMPLERSPROC,    DeleteSamplers)
REGISTRY_OPENGL(PFNGLBINDSAMPLERPROC,       BindSampler)
REGISTRY_OPENGL(PFNGLSAMPLERPARAMETERIPROC, SamplerParameteri)
// >= 4.5
REGISTRY_OPENGL(PFNGLCREATESAMPLERSPROC, CreateSamplers)

// MESHES
// >= 2.0
REGISTRY_OPENGL(PFNGLGENBUFFERSPROC,               GenBuffers)
REGISTRY_OPENGL(PFNGLDELETEBUFFERSPROC,            DeleteBuffers)
REGISTRY_OPENGL(PFNGLBINDBUFFERPROC,               BindBuffer)
REGISTRY_OPENGL(PFNGLBUFFERDATAPROC,               BufferData)
REGISTRY_OPENGL(PFNGLDISABLEVERTEXATTRIBARRAYPROC, DisableVertexAttribArray)
REGISTRY_OPENGL(PFNGLENABLEVERTEXATTRIBARRAYPROC,  EnableVertexAttribArray)
REGISTRY_OPENGL(PFNGLVERTEXATTRIBPOINTERPROC,      VertexAttribPointer)
REGISTRY_OPENGL(PFNGLBUFFERSUBDATAPROC,            BufferSubData)
// >= 3.0
REGISTRY_OPENGL(PFNGLGENVERTEXARRAYSPROC,    GenVertexArrays)
REGISTRY_OPENGL(PFNGLDELETEVERTEXARRAYSPROC, DeleteVertexArrays)
REGISTRY_OPENGL(PFNGLBINDVERTEXARRAYPROC,    BindVertexArray)
// >= 4.3
REGISTRY_OPENGL(PFNGLBINDVERTEXBUFFERPROC,    BindVertexBuffer)
REGISTRY_OPENGL(PFNGLVERTEXATTRIBFORMATPROC,  VertexAttribFormat)
REGISTRY_OPENGL(PFNGLVERTEXATTRIBBINDINGPROC, VertexAttribBinding)
// >= 4.5
REGISTRY_OPENGL(PFNGLCREATEVERTEXARRAYSPROC,       CreateVertexArrays)
REGISTRY_OPENGL(PFNGLCREATEBUFFERSPROC,            CreateBuffers)
REGISTRY_OPENGL(PFNGLNAMEDBUFFERDATAPROC,          NamedBufferData)
REGISTRY_OPENGL(PFNGLVERTEXARRAYELEMENTBUFFERPROC, VertexArrayElementBuffer)
REGISTRY_OPENGL(PFNGLVERTEXARRAYVERTEXBUFFERPROC,  VertexArrayVertexBuffer)
REGISTRY_OPENGL(PFNGLDISABLEVERTEXARRAYATTRIBPROC, DisableVertexArrayAttrib)
REGISTRY_OPENGL(PFNGLENABLEVERTEXARRAYATTRIBPROC,  EnableVertexArrayAttrib)
REGISTRY_OPENGL(PFNGLVERTEXARRAYATTRIBFORMATPROC,  VertexArrayAttribFormat)
REGISTRY_OPENGL(PFNGLVERTEXARRAYATTRIBBINDINGPROC, VertexArrayAttribBinding)
REGISTRY_OPENGL(PFNGLNAMEDBUFFERSUBDATAPROC,       NamedBufferSubData)

// DISPLAY
REGISTRY_OPENGL(PFNGLDRAWELEMENTSPROC, DrawElements)
REGISTRY_OPENGL(PFNGLDRAWARRAYSPROC,   DrawArrays)
REGISTRY_OPENGL(PFNGLCLEARPROC,        Clear)
REGISTRY_OPENGL(PFNGLFINISHPROC,       Finish)
REGISTRY_OPENGL(PFNGLFLUSHPROC,        Flush)
#undef REGISTRY_OPENGL
