// EXTENSIONS
REGISTRY_OPENGL(PFNGLGETINTEGERVPROC, GetIntegerv)
REGISTRY_OPENGL(PFNGLGETSTRINGIPROC,  GetStringi)

// SETTINGS
REGISTRY_OPENGL(PFNGLCLIPCONTROLPROC, ClipControl) // >= 4.5

REGISTRY_OPENGL(PFNGLDISABLEPROC, Disable)
REGISTRY_OPENGL(PFNGLENABLEPROC,  Enable)

REGISTRY_OPENGL(PFNGLDEPTHMASKPROC,   DepthMask)
REGISTRY_OPENGL(PFNGLDEPTHRANGEPROC,  DepthRange)  // >= 2.0
REGISTRY_OPENGL(PFNGLDEPTHRANGEFPROC, DepthRangef) // >= 4.1
REGISTRY_OPENGL(PFNGLDEPTHFUNCPROC,   DepthFunc)
REGISTRY_OPENGL(PFNGLCLEARDEPTHPROC,  ClearDepth)  // >= 2.0
REGISTRY_OPENGL(PFNGLCLEARDEPTHFPROC, ClearDepthf) // >= 4.1

REGISTRY_OPENGL(PFNGLCOLORMASKPROC,  ColorMask)
REGISTRY_OPENGL(PFNGLCLEARCOLORPROC, ClearColor)
REGISTRY_OPENGL(PFNGLBLENDFUNCIPROC, BlendFunc)

REGISTRY_OPENGL(PFNGLCULLFACEPROC,  CullFace)
REGISTRY_OPENGL(PFNGLFRONTFACEPROC, FrontFace)

REGISTRY_OPENGL(PFNGLCLEARSTENCILPROC, ClearStencil)
REGISTRY_OPENGL(PFNGLSTENCILMASKPROC,  StencilMask)
REGISTRY_OPENGL(PFNGLSTENCILFUNCPROC,  StencilFunc)
REGISTRY_OPENGL(PFNGLSTENCILOPPROC,    StencilOp)

// SHADERS
REGISTRY_OPENGL(PFNGLCREATEPROGRAMPROC, CreateProgram)
REGISTRY_OPENGL(PFNGLCREATESHADERPROC,  CreateShader)

// TEXTURES
// >= 2.0
REGISTRY_OPENGL(PFNGLGENTEXTURESPROC,    GenTextures)
REGISTRY_OPENGL(PFNGLDELETETEXTURESPROC, DeleteTextures)
REGISTRY_OPENGL(PFNGLBINDTEXTUREPROC,    BindTexture)
REGISTRY_OPENGL(PFNGLTEXIMAGE2DPROC,     TexImage2D)
REGISTRY_OPENGL(PFNGLTEXPARAMETERIPROC,  TexParameteri)
REGISTRY_OPENGL(PFNGLACTIVETEXTUREPROC,  ActiveTexture)
// >= 4.2
REGISTRY_OPENGL(PFNGLTEXSTORAGE2DPROC, TexStorage2D)
// >= 4.5
REGISTRY_OPENGL(PFNGLCREATETEXTURESPROC,    CreateTextures)
REGISTRY_OPENGL(PFNGLTEXTURESTORAGE2DPROC,  TextureStorage2D)
REGISTRY_OPENGL(PFNGLTEXTUREPARAMETERIPROC, TextureParameteri)
REGISTRY_OPENGL(PFNGLBINDTEXTUREUNITPROC,   BindTextureUnit)

// SAMPLERS
// >= 3.2
REGISTRY_OPENGL(PFNGLGENSAMPLERSPROC,       GenSamplers)
REGISTRY_OPENGL(PFNGLDELETESAMPLERSPROC,    DeleteSamplers)
REGISTRY_OPENGL(PFNGLBINDSAMPLERPROC,       BindSampler)
REGISTRY_OPENGL(PFNGLSAMPLERPARAMETERIPROC, SamplerParameteri)
// >= 4.5
REGISTRY_OPENGL(PFNGLCREATESAMPLERSPROC, CreateSamplers)

// MESHES
// >= 2.0
REGISTRY_OPENGL(PFNGLGENBUFFERSPROC,               GenBuffers)
REGISTRY_OPENGL(PFNGLBINDBUFFERPROC,               BindBuffer)
REGISTRY_OPENGL(PFNGLBUFFERDATAPROC,               BufferData)
REGISTRY_OPENGL(PFNGLDISABLEVERTEXATTRIBARRAYPROC, DisableVertexAttribArray)
REGISTRY_OPENGL(PFNGLENABLEVERTEXATTRIBARRAYPROC,  EnableVertexAttribArray)
REGISTRY_OPENGL(PFNGLVERTEXATTRIBPOINTERPROC,      VertexAttribPointer)
// >= 3.0
REGISTRY_OPENGL(PFNGLGENVERTEXARRAYSPROC, GenVertexArrays)
REGISTRY_OPENGL(PFNGLBINDVERTEXARRAYPROC, BindVertexArray)
// >= 4.3
REGISTRY_OPENGL(PFNGLBINDVERTEXBUFFERPROC,    BindVertexBuffer)
REGISTRY_OPENGL(PFNGLVERTEXATTRIBFORMATPROC,  VertexAttribFormat)
REGISTRY_OPENGL(PFNGLVERTEXATTRIBBINDINGPROC, VertexAttribBinding)
// >= 4.5
REGISTRY_OPENGL(PFNGLCREATEVERTEXARRAYSPROC,       CreateVertexArrays)
REGISTRY_OPENGL(PFNGLCREATEBUFFERSPROC,            CreateBuffers)
REGISTRY_OPENGL(PFNGLNAMEDBUFFERDATAPROC,          NamedBufferData)
REGISTRY_OPENGL(PFNGLVERTEXARRAYELEMENTBUFFERPROC, VertexArrayElementBuffer)
REGISTRY_OPENGL(PFNGLVERTEXARRAYVERTEXBUFFERPROC,  VertexArrayVertexBuffer)
REGISTRY_OPENGL(PFNGLDISABLEVERTEXARRAYATTRIBPROC, DisableVertexArrayAttrib)
REGISTRY_OPENGL(PFNGLENABLEVERTEXARRAYATTRIBPROC,  EnableVertexArrayAttrib)
REGISTRY_OPENGL(PFNGLVERTEXARRAYATTRIBFORMATPROC,  VertexArrayAttribFormat)
REGISTRY_OPENGL(PFNGLVERTEXARRAYATTRIBBINDINGPROC, VertexArrayAttribBinding)

// display
REGISTRY_OPENGL(PFNGLFINISHPROC, Finish)
REGISTRY_OPENGL(PFNGLFLUSHPROC,  Flush)
#undef REGISTRY_OPENGL
