#if !defined(ENGINE_ASCII)
#define ENGINE_ASCII

enum ASCII {
	// control
	ASCII_NUL = '\0',
	ASCII_SOH,
	ASCII_STX,
	ASCII_ETX,
	ASCII_EOT,
	ASCII_ENQ,
	ASCII_ACK,
	ASCII_BEL = '\a',
	ASCII_BS  = '\b',
	ASCII_HT  = '\t',
	ASCII_LF  = '\n',
	ASCII_VT  = '\v',
	ASCII_FF  = '\f',
	ASCII_CR  = '\r',
	ASCII_SO,
	ASCII_SI,
	ASCII_DLE,
	ASCII_DC1,
	ASCII_DC2,
	ASCII_DC3,
	ASCII_DC4,
	ASCII_NAK,
	ASCII_SYN,
	ASCII_ETB,
	ASCII_CAN,
	ASCII_EM,
	ASCII_SUB,
	ASCII_ESC = 0x1B,
	ASCII_FS,
	ASCII_GS,
	ASCII_RS,
	ASCII_US,
	// printable
	ASCII_Space       = ' ',
	ASCII_Exclamation = '!',
	ASCII_QuoteDouble = '"',
	ASCII_Number      = '#',
	ASCII_Dollar      = '$',
	ASCII_Percent     = '%',
	ASCII_Ampersand   = '&',
	ASCII_QuoteSingle = '\'',
	ASCII_CircleL = '(',
	ASCII_CircleR = ')',
	ASCII_Mul   = '*',
	ASCII_Add   = '+',
	ASCII_Comma = ',',
	ASCII_Sub   = '-',
	ASCII_Dot   = '.',
	ASCII_Div   = '/',
	ASCII_0 = '0',
	ASCII_1 = '1',
	ASCII_2 = '2',
	ASCII_3 = '3',
	ASCII_4 = '4',
	ASCII_5 = '5',
	ASCII_6 = '6',
	ASCII_7 = '7',
	ASCII_8 = '8',
	ASCII_9 = '9',
	ASCII_Colon     = ':',
	ASCII_Semicolon = ';',
	ASCII_AngleL    = '<',
	ASCII_Equals    = '=',
	ASCII_AngleR    = '>',
	ASCII_Question  = '?',
	ASCII_At = '@',
	ASCII_A = 'A',
	ASCII_B = 'B',
	ASCII_C = 'C',
	ASCII_D = 'D',
	ASCII_E = 'E',
	ASCII_F = 'F',
	ASCII_G = 'G',
	ASCII_H = 'H',
	ASCII_I = 'I',
	ASCII_J = 'J',
	ASCII_K = 'K',
	ASCII_L = 'L',
	ASCII_M = 'M',
	ASCII_N = 'N',
	ASCII_O = 'O',
	ASCII_P = 'P',
	ASCII_Q = 'Q',
	ASCII_R = 'R',
	ASCII_S = 'S',
	ASCII_T = 'T',
	ASCII_U = 'U',
	ASCII_V = 'V',
	ASCII_W = 'W',
	ASCII_X = 'X',
	ASCII_Y = 'Y',
	ASCII_Z = 'Z',
	ASCII_SquareL    = '[',
	ASCII_Backslash  = '\\',
	ASCII_SquareR    = ']',
	ASCII_Circumflex = '^',
	ASCII_Underscore = '_',
	ASCII_Backtick   = '`',
	ASCII_a = 'a',
	ASCII_b = 'b',
	ASCII_c = 'c',
	ASCII_d = 'd',
	ASCII_e = 'e',
	ASCII_f = 'f',
	ASCII_g = 'g',
	ASCII_h = 'h',
	ASCII_i = 'i',
	ASCII_j = 'j',
	ASCII_k = 'k',
	ASCII_l = 'l',
	ASCII_m = 'm',
	ASCII_n = 'n',
	ASCII_o = 'o',
	ASCII_p = 'p',
	ASCII_q = 'q',
	ASCII_r = 'r',
	ASCII_s = 's',
	ASCII_t = 't',
	ASCII_u = 'u',
	ASCII_v = 'v',
	ASCII_w = 'w',
	ASCII_x = 'x',
	ASCII_y = 'y',
	ASCII_z = 'z',
	ASCII_CurlyL   = '{',
	ASCII_Vertical = '|',
	ASCII_CurlyR   = '}',
	ASCII_Tilde    = '~',
	ASCII_Delete   = 0x7f,
	// extended
	ASCII_0x80 = 0x80,
	ASCII_0xff = 0xff,
};

#endif // ENGINE_ASCII
