#include "engine/api/code.h"

#include "api/time_system.h"
#include "api/window_system.h"
#include "api/opengl_system.h"

#include <Windows.h>
#include <signal.h>
#include <ShellScalingApi.h>

//
static void impl_set_process_dpi_awareness(void);
static void impl_signal_handler(int value);

//
// API
//

#include "engine/api/platform_system.h"

bool engine_system_should_close;

void engine_system_init(void) {
	impl_set_process_dpi_awareness();

	engine_time_system_init();
	engine_window_system_init();
	engine_opengl_system_init();

	signal(SIGABRT, impl_signal_handler);
	signal(SIGFPE,  impl_signal_handler);
	signal(SIGILL,  impl_signal_handler);
	signal(SIGINT,  impl_signal_handler);
	signal(SIGSEGV, impl_signal_handler);
	signal(SIGTERM, impl_signal_handler);
}

void engine_system_deinit(void) {
	engine_time_system_deinit();
	engine_window_system_deinit();
	engine_opengl_system_deinit();
}

void engine_system_poll_events(void) {
	MSG message;
	while (PeekMessageA(&message, 0, 0, 0, PM_REMOVE)) {
		if (message.message == WM_QUIT) { engine_system_should_close = true; continue; }
		TranslateMessage(&message);
		DispatchMessageA(&message);
	}
}

//
// API internal
//

#include "api/system_internal.h"

void engine_system_internal_log_last_error(void) {
	DWORD const error = GetLastError();
	if (!error) { return; }

	LPTSTR buffer = NULL;
	FormatMessageA(
		FORMAT_MESSAGE_FROM_SYSTEM
		| FORMAT_MESSAGE_ALLOCATE_BUFFER
		| FORMAT_MESSAGE_IGNORE_INSERTS
		| FORMAT_MESSAGE_MAX_WIDTH_MASK,
		NULL, error,
		MAKELANGID(LANG_ENGLISH, SUBLANG_DEFAULT),
		(LPTSTR)&buffer, 0,
		NULL
	);

	printf("'0x%lx': %s\n", error, buffer ? buffer : "unknown");
	if (buffer) { LocalFree(buffer); }
}

//
// internal implementation
//

static void impl_set_process_dpi_awareness(void) {
	// https://docs.microsoft.com/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process
	HMODULE User32_dll = LoadLibraryA("User32.dll");
	if (!User32_dll) { return; }

	bool done = false;

	if (!done) { // Windows 10, version 1703
		BOOL (WINAPI * _SetProcessDpiAwarenessContext)(DPI_AWARENESS_CONTEXT) = (BOOL (WINAPI *)(DPI_AWARENESS_CONTEXT value))GetProcAddress(User32_dll, "SetProcessDpiAwarenessContext");
		if (_SetProcessDpiAwarenessContext) { _SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2); done = true; }
	}

	if (!done) { // Windows 8.1
		HMODULE Shcore_dll = LoadLibraryA("Shcore.dll");
		if (Shcore_dll) {
			BOOL (WINAPI * _SetProcessDpiAwareness)(PROCESS_DPI_AWARENESS) = (BOOL (WINAPI *)(PROCESS_DPI_AWARENESS))GetProcAddress(Shcore_dll, "SetProcessDpiAwareness");
			if (_SetProcessDpiAwareness) { _SetProcessDpiAwareness(PROCESS_PER_MONITOR_DPI_AWARE); done = true; }
			FreeLibrary(Shcore_dll);
		}
	}

	if (!done) { // Windows Vista
		BOOL (WINAPI * _SetProcessDPIAware)(VOID) = (BOOL (WINAPI *)(VOID))GetProcAddress(User32_dll, "SetProcessDPIAware");
		if (_SetProcessDPIAware) { _SetProcessDPIAware(); done = true; }
	}

	FreeLibrary(User32_dll);
}

static void impl_signal_handler(int value) {
	// http://www.cplusplus.com/reference/csignal/signal/
	switch (value) {
		case SIGABRT: ENGINE_DEBUG_BREAK(); break; // Abnormal termination, such as is initiated by the abort function.
		case SIGFPE:  ENGINE_DEBUG_BREAK(); break; // Erroneous arithmetic operation, such as zero divide or an operation resulting in overflow (not necessarily with a floating-point operation).
		case SIGILL:  ENGINE_DEBUG_BREAK(); break; // Invalid function image, such as an illegal instruction. This is generally due to a corruption in the code or to an attempt to execute data.
		case SIGINT:  ENGINE_DEBUG_BREAK(); break; // Interactive attention signal. Generally generated by the application user.
		case SIGSEGV: ENGINE_DEBUG_BREAK(); break; // Invalid access to storage: When a program tries to read or write outside the memory it has allocated.
		case SIGTERM: ENGINE_DEBUG_BREAK(); break; // Termination request sent to program.
		default:      ENGINE_DEBUG_BREAK(); break; // ?
	}
	engine_system_should_close = true;
}

// https://docs.microsoft.com/cpp/c-runtime-library/argc-argv-wargv
// https://docs.microsoft.com/windows/win32/desktop-programming
// https://docs.microsoft.com/windows/win32/dlls/dllmain
// https://docs.microsoft.com/windows/win32/learnwin32/winmain--the-application-entry-point
// https://docs.microsoft.com/cpp/build/reference/subsystem-specify-subsystem

extern int main(int argc, char * argv[]);
int WINAPI WinMain(
	HINSTANCE hInstance,     // is something called a "handle to an instance" or "handle to a module." The operating system uses this value to identify the executable (EXE) when it is loaded in memory. The instance handle is needed for certain Windows functions—for example, to load icons or bitmaps.
	HINSTANCE hPrevInstance, // has no meaning. It was used in 16-bit Windows, but is now always zero.
	PSTR      pCmdLine,      // contains the command-line arguments as an ANSI string.
	int       nCmdShow       // is a flag that says whether the main application window will be minimized, maximized, or shown normally.
) {
	(void)hInstance; (void)hPrevInstance; (void)pCmdLine; (void)nCmdShow;
	return main(__argc, __argv);
}

//
// graphics cards supplements
//

#if defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wmissing-variable-declarations"
#endif

// http://developer.download.nvidia.com/devzone/devcenter/gamegraphics/files/OptimusRenderingPolicies.pdf
__declspec(dllexport) DWORD NvOptimusEnablement = 0x00000001UL;

// https://community.amd.com/thread/169965
// https://community.amd.com/thread/223376
// https://gpuopen.com/amdpowerxpressrequesthighperformance/
__declspec(dllexport) DWORD AmdPowerXpressRequestHighPerformance = 0x00000001UL;

#if defined(__clang__)
#pragma clang diagnostic pop
#endif
